import groovy.json.JsonSlurper
pipeline {
    agent {
          ecs {
                inheritFrom "jenkins-agent"
                 }
            } 

    stages {
                stage('Check Approval Status') {
            steps {
                script {
                    def jobType = "OOSQ0001"
                    def apiUrl = "https://jenkins.dev.webserver.insulet.com/approval/get_next_job.php?type=${jobType}"
                    def jobNumberRaw = sh(
                        script: "curl -s -k '${apiUrl}' | sed '/^\\s*\$/d'",
                        returnStdout: true
                    ).trim()

                    echo "API response (filtered): '${jobNumberRaw}'"

                    if (!jobNumberRaw) {
                        error "No job available for type ${jobType}. Skipping execution."

                    }

                    def jobNumber = jobNumberRaw.toInteger()
                    echo " Valid job number received: ${jobNumber}"

                    env.JOB_ID = jobNumber.toString()
                }
            }
        }

        stage('Fetch Parameters from Job File') {
            steps {
                script {
                    def jobFilePath = sh(script: "mktemp", returnStdout: true).trim()
                    def fetchUrl = "https://jenkins.dev.webserver.insulet.com/approval/fetch_job_file.php?jobid=${env.JOB_ID}"

                    echo "📄 Fetching jobfile from ${fetchUrl}"
                    echo "📄 Temp job file path: ${jobFilePath}"

                    sh """
                        curl -sk '${fetchUrl}' -o '${jobFilePath}'
                    """

                    def lines = readFile(jobFilePath).readLines()
                    for (line in lines) {
                        line = line.trim()
                        if (line.startsWith("#") || line.isEmpty()) continue
                        def (key, value) = line.tokenize("=")
                        key = key?.trim()?.toUpperCase()
                        value = value?.trim()?.replaceAll(/^"|"$/, '')
                        if (key && value) {
                            echo "Setting env: ${key}=${value}"
                            env."${key}" = value
                        }
                    }

                    sh "rm -f '${jobFilePath}'"
                }
            }
        }         
        stage('SQS redrive Process') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("https://jenkins.dev.webserver.insulet.com/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) // Since retList contains only one value, assign it to the global awsRegion variable 
                    awsRegion = retList[0] 
                    sh """
                    aws --profile ${awsProfile} --region ${awsRegion} sqs get-queue-attributes --queue-url ${env.SQS_Queue_URL} --attribute-names ApproximateNumberOfMessages ApproximateNumberOfMessagesNotVisible
                    aws --profile ${awsProfile} --region ${awsRegion} sqs start-message-move-task --source-arn ${env.SQS_ARN} --max-number-of-messages-per-second ${env.Max_Messages_ps}
                    """
                }
            }
        }

        stage('Monitor process until ApproximateNumberOfMessages is 0 ') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("https://jenkins.dev.webserver.insulet.com/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) // Since retList contains only one value, assign it to the global awsRegion variable 
                    awsRegion = retList[0] 
                    sh """
                    sleep 15
                    aws --profile ${awsProfile}  --region ${awsRegion} sqs get-queue-attributes --queue-url ${env.SQS_Queue_URL} --attribute-names ApproximateNumberOfMessages ApproximateNumberOfMessagesNotVisible
                    """
                }
            }
        }
    }
}
