pipeline {
    agent {
          ecs {
                inheritFrom "jenkins-agent"
                 }
            }  

    stages {
            stage('Check Approval Status') {
            steps {
                script {
                    def jobType = "OOMF0001"
                    def apiUrl = "https://jenkins.dev.webserver.insulet.com/approval/get_next_job.php?type=${jobType}"
                    def jobNumberRaw = sh(
                        script: "curl -s -k '${apiUrl}' | sed '/^\\s*\$/d'",
                        returnStdout: true
                    ).trim()

                    echo "API response (filtered): '${jobNumberRaw}'"

                    if (!jobNumberRaw) {
                        error "No job available for type ${jobType}. Skipping execution."

                    }

                    def jobNumber = jobNumberRaw.toInteger()
                    echo "✔️ Valid job number received: ${jobNumber}"

                    env.JOB_ID = jobNumber.toString()
                }
            }
        }

        stage('Fetch Parameters from Job File') {
            steps {
                script {
                    def jobFilePath = sh(script: "mktemp", returnStdout: true).trim()
                    def fetchUrl = "https://jenkins.dev.webserver.insulet.com/approval/fetch_job_file.php?jobid=${env.JOB_ID}"

                    echo "📄 Fetching jobfile from ${fetchUrl}"
                    echo "📄 Temp job file path: ${jobFilePath}"

                    sh """
                        curl -sk '${fetchUrl}' -o '${jobFilePath}'
                    """

                    def lines = readFile(jobFilePath).readLines()
                    for (line in lines) {
                        line = line.trim()
                        if (line.startsWith("#") || line.isEmpty()) continue
                        def (key, value) = line.tokenize("=")
                        key = key?.trim()?.toUpperCase()
                        value = value?.trim()?.replaceAll(/^"|"$/, '')
                        if (key && value) {
                            echo "Setting env: ${key}=${value}"
                            env."${key}" = value
                        }
                    }

                    sh "rm -f '${jobFilePath}'"
                }
            }
        }  
        
        stage('Make API Request') {
            environment {
                // Define environment variables for MongoDB API
                // M_API_KEY = credentials('mongoApiKey')  // Jenkins credential for API key
                M_API_URL = 'https://cloud.mongodb.com/api/public/v1.0/groups?pretty=true'
                M_CLIENT_AUTH = credentials('client-auth-mongo-token')
    }
            steps {
                script {
                    // Split the environment variable into an array 
                    def MongoClusterVar = env.MONGO_CLUSTER_NAME.split(',') 
                    // Assign the first element 
                    def MongoCluster = MongoClusterVar[0] 
                    // Assign the second element 
                    def ProjectID = MongoClusterVar[1] 
                    // Print values to verify 
                    echo "MongoCluster: ${MongoCluster}" 
                    echo "ProjectID: ${ProjectID}"                    
                        def apiResponse = sh(
                    script: """
                            curl --request POST --url https://cloud.mongodb.com/api/oauth/token --header 'accept: application/json'  --header 'cache-control: no-cache' --header 'authorization: Basic '$M_CLIENT_AUTH'' --header 'content-type: application/x-www-form-urlencoded' --data 'grant_type=client_credentials'
                        """,
                        returnStdout: true
                        ).trim()                        
                        echo "apiResponse: ${apiResponse}"
                        // Use Groovy's replaceFirst to extract the actual token
                        def token = apiResponse.replaceFirst(/.*"access_token":"([^"]+)".*/, '$1')
                        println "Extracted token: ${token}"
                        def apiFailover = sh(
                    script: """
                            curl --request POST --header 'Authorization: Bearer ${token}' --header "Accept: application/vnd.atlas.2024-08-05+json" --include \\ --request POST "https://cloud.mongodb.com/api/atlas/v2/groups/${ProjectID}/clusters/${MongoCluster}/restartPrimaries"
                        """,
                        returnStdout: true
                        ).trim()
                         println "Failover Complete: ${apiFailover}"
                }
            }
        }
    }
}
