pipeline {
    agent {
        ecs {
            inheritFrom "jenkins-agent"
        }
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
