import groovy.json.JsonSlurper
pipeline {
    agent {
          ecs {
                inheritFrom "jenkins-agent"
                 }
            } 
    // environment {
      // AWS_DEFAULT_REGION = "us-east-1"
      //  ENVIRONMENT = "${env.ENVIRONMENT}"
      //  REDIS_CLUSTER_NAME = "${env.REDIS_CLUSTER_NAME}"
    // }

    stages {
        stage('Check Approval Status') {
            steps {
                script {
                    def jobType = "OORF0001"
                    def apiUrl = "https://jenkins.dev.webserver.insulet.com/approval/get_next_job.php?type=${jobType}"
                    def jobNumberRaw = sh(
                        script: "curl -s -k '${apiUrl}' | sed '/^\\s*\$/d'",
                        returnStdout: true
                    ).trim()

                    echo "API response (filtered): '${jobNumberRaw}'"

                    if (!jobNumberRaw) {
                        error "No job available for type ${jobType}. Skipping execution."

                    }

                    def jobNumber = jobNumberRaw.toInteger()
                    echo "✔️ Valid job number received: ${jobNumber}"

                    env.JOB_ID = jobNumber.toString()
                }
            }
        }

        stage('Fetch Parameters from Job File') {
            steps {
                script {
                    def jobFilePath = sh(script: "mktemp", returnStdout: true).trim()
                    def fetchUrl = "https://jenkins.dev.webserver.insulet.com/approval/fetch_job_file.php?jobid=${env.JOB_ID}"

                    echo "📄 Fetching jobfile from ${fetchUrl}"
                    echo "📄 Temp job file path: ${jobFilePath}"

                    sh """
                        curl -sk '${fetchUrl}' -o '${jobFilePath}'
                    """

                    def lines = readFile(jobFilePath).readLines()
                    for (line in lines) {
                        line = line.trim()
                        if (line.startsWith("#") || line.isEmpty()) continue
                        def (key, value) = line.tokenize("=")
                        key = key?.trim()?.toUpperCase()
                        value = value?.trim()?.replaceAll(/^"|"$/, '')
                        if (key && value) {
                            echo "Setting env: ${key}=${value}"
                            env."${key}" = value
                        }
                    }

                    sh "rm -f '${jobFilePath}'"
                }
            }
        }  
        stage('Redis Failover test') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def redisClusterName = env.REDIS_CLUSTER_NAME.replaceAll(",", "")
                    def data = new URL("http://10.200.2.219/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) 
                    awsRegion = retList[0]
                    sh """
                        export AWS_PROFILE=${awsProfile}
                        aws --profile ${awsProfile} --region ${awsRegion} elasticache test-failover --replication-group-id ${redisClusterName} --node-group-id "0001"
                    """
                }
            }
        }

        stage('Status update') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def redisClusterName = env.REDIS_CLUSTER_NAME.replaceAll(",", "")
                    def data = new URL("http://10.200.2.219/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) 
                    awsRegion = retList[0]
                    
                    sh """
                        export AWS_PROFILE=${awsProfile}
                        sleep 15
                        aws --profile ${awsProfile}  --region ${awsRegion} elasticache describe-replication-groups --replication-group-id ${redisClusterName}
                        sleep 120
                        aws --profile ${awsProfile}  --region ${awsRegion} elasticache describe-replication-groups --replication-group-id ${redisClusterName}
                    """
                }
            }
        }
    }
}
