import groovy.json.JsonSlurper
pipeline {
    
    agent {
          ecs {
                inheritFrom "jenkins-agent"
                 }
            }   
    environment {
        AWS_DEFAULT_REGION = "${env.AWS_DEFAULT_REGION}"
        AWS_PROFILE = "${env.AWS_PROFILE}"
        PHOME = '/home/jenkins/workspace/Cloud_Ops/Omnipod-Operations-TemporaryParmChange'
        STACK_NAME = "${env.STACK_NAME}"
        PARMFILE = "${PHOME}/${env.STACK_NAME}.parm.json"
        REVERTFILE = "${PHOME}/${env.STACK_NAME}.revert.json"
        SERVICE_PREFIX = "${STACK_NAME}".replaceAll(/^(qa|test)-/, '')
        CLUSTER_NAME = "${env.CLUSTER_NAME}".replaceAll(",", "")
    }

    stages {
        stage('Get Existing Parameters') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("http://10.200.2.179/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data)
                    awsRegion = retList[0] 
                    sh """
                        aws cloudformation describe-stacks --region ${awsRegion} --profile ${awsProfile} --stack-name '${STACK_NAME}' --query 'Stacks[0].Parameters' > ${REVERTFILE}
                    """
                }
            }
        }
        
        stage('Create Parameter File') {
            steps {
                script {
                    def revertJson = readFile("${REVERTFILE}")
                    def parameters = new groovy.json.JsonSlurperClassic().parseText(revertJson)

                    def ParameterKey = params.PARAMETER_KEY ?: error("Parameter Key parameter is not defined")
                    def ParameterValue = params.PARAMETER_VALUE ?: error("Parameter Value parameter is not defined")

                    // Initialize a map to hold the parameters for easy lookup and modification
                    def paramMap = [:]

                    // Populate the map with existing parameters
                    parameters.each { param ->
                        paramMap[param.ParameterKey] = param.ParameterValue
                    }

                    // Update the parameter if it exists, otherwise add it
                    paramMap[ParameterKey] = ParameterValue

                    // Convert the map back to the list format required for the JSON
                    def formattedParams = paramMap.collect { key, value ->
                        [ParameterKey: key, ParameterValue: value]
                    }

                    def updatedJson = new groovy.json.JsonBuilder(formattedParams).toPrettyString()
                    writeFile file: "${PHOME}/${env.STACK_NAME}.parm.json", text: updatedJson
                    echo "Generated JSON for Parameter Change" 
                }
            }
        }
        
        stage('Update Stack with Parameter File') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("http://10.200.2.179/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data)
                    awsRegion = retList[0] 
                    sh """
                        date
                        aws cloudformation update-stack --region ${awsRegion} --profile ${awsProfile} --stack-name '${STACK_NAME}' --use-previous-template --capabilities CAPABILITY_NAMED_IAM --parameters file://${PARMFILE}
                        aws cloudformation wait stack-update-complete --region ${awsRegion} --profile ${awsProfile} --stack-name ${STACK_NAME}
                    """
                }
            }
        }
        
        stage('Check ECS Service Last Restart Time') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("http://10.200.2.179/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) // Since retList contains only one value, assign it to the global awsRegion variable 
                    awsRegion = retList[0]
                    def serviceName = "${env.SERVICE_PREFIX}".replaceAll(/^(qa|test|int|perf)-/, '')
                    def taskArnsJson = sh(script: "aws ecs list-tasks --region ${awsRegion} --profile ${awsProfile} --cluster ${CLUSTER_NAME} --service-name ${serviceName} --query 'taskArns' --output json", returnStdout: true).trim()
                    def taskArns = new groovy.json.JsonSlurperClassic().parseText(taskArnsJson)

                    if (taskArns.size() == 0) {
                        echo "No tasks found for ECS service ${serviceName} in cluster ${CLUSTER_NAME}."
                        return
                    }

                    def tasksJson = sh(script: "aws ecs describe-tasks --region ${awsRegion} --profile ${awsProfile} --cluster ${CLUSTER_NAME} --tasks ${taskArns.join(' ')} --query 'tasks[].[taskArn,startedAt]' --output json", returnStdout: true).trim()
                    def tasks = new groovy.json.JsonSlurperClassic().parseText(tasksJson)
                    def mostRecentTask = tasks.sort { -it[1] }.first()

                    if (mostRecentTask) {
                        echo "Most recently started task ARN: ${mostRecentTask[0]}"
                        echo "Started at: ${mostRecentTask[1]}"
                    def isoDate = "${mostRecentTask[1]}"
                    def parsedDate = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX").parse(isoDate)
                    def epochMillis = parsedDate.time
                    def epochSeconds = epochMillis / 1000
                    
                    echo "ISO 8601 date: ${isoDate}"
                    echo "Epoch (Unix timestamp in milliseconds): ${epochMillis}"
                    echo "Epoch (Unix timestamp in seconds): ${epochSeconds}"
                        calculateAndActOnStackAge("${epochMillis}")
                    } else {
                        echo "Unable to determine the most recent task start time for ECS service ${serviceName}"
                    }
                }
            }
        }
        
        stage('Wait for Specified Minutes') {
            steps {
                script {
                    sleep time: "${env.DURATION}", unit: 'MINUTES'
                }
            }
        }
        
        stage('Revert Parameter Name') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("http://10.200.2.179/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data)
                    awsRegion = retList[0]
                    
                    sh """
                        aws cloudformation update-stack --region ${awsRegion} --profile ${awsProfile} --stack-name '${STACK_NAME}' --use-previous-template --capabilities CAPABILITY_NAMED_IAM --parameters file://${REVERTFILE}
                        aws cloudformation wait stack-update-complete --region ${awsRegion} --profile ${awsProfile} --stack-name ${STACK_NAME}
                    """
                }
            }
        }
        stage('Check ECS Service Last Restart Time again') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def data = new URL("http://10.200.2.179/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) // Since retList contains only one value, assign it to the global awsRegion variable 
                    awsRegion = retList[0]
                    def serviceName = "${env.SERVICE_PREFIX}".replaceAll(/^(qa|test|int|perf)-/, '')
                    def taskArnsJson = sh(script: "aws ecs list-tasks --region ${awsRegion} --profile ${awsProfile} --cluster ${CLUSTER_NAME} --service-name ${serviceName} --query 'taskArns' --output json", returnStdout: true).trim()
                    def taskArns = new groovy.json.JsonSlurperClassic().parseText(taskArnsJson)

                    if (taskArns.size() == 0) {
                        echo "No tasks found for ECS service ${serviceName} in cluster ${CLUSTER_NAME}."
                        return
                    }

                    def tasksJson = sh(script: "aws ecs describe-tasks --region ${awsRegion} --profile ${awsProfile} --cluster ${CLUSTER_NAME} --tasks ${taskArns.join(' ')} --query 'tasks[].[taskArn,startedAt]' --output json", returnStdout: true).trim()
                    def tasks = new groovy.json.JsonSlurperClassic().parseText(tasksJson)
                    def mostRecentTask = tasks.sort { -it[1] }.first()

                    if (mostRecentTask) {
                        echo "Most recently started task ARN: ${mostRecentTask[0]}"
                        echo "Started at: ${mostRecentTask[1]}"
                    def isoDate = "${mostRecentTask[1]}"
                    def parsedDate = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX").parse(isoDate)
                    def epochMillis = parsedDate.time
                    def epochSeconds = epochMillis / 1000
                    
                    echo "ISO 8601 date: ${isoDate}"
                    echo "Epoch (Unix timestamp in milliseconds): ${epochMillis}"
                    echo "Epoch (Unix timestamp in seconds): ${epochSeconds}"
                        calculateAndActOnStackAge("${epochMillis}")
                    } else {
                        echo "Unable to determine the most recent task start time for ECS service ${serviceName}"
                    }
                }
            }
        }
    }
}

def calculateAndActOnStackAge(String taskStartTime) {
    if (taskStartTime == null || taskStartTime.isEmpty()) {
        echo "Task start time is null or empty, skipping ECS service restart check. $taskStartTime "
        return
    }
    def timestampMillis = Long.parseLong(taskStartTime)
    def currentTimeMillis = System.currentTimeMillis()
    def elapsedMillis = currentTimeMillis - timestampMillis
    def elapsedMinutes = elapsedMillis / (60000)
  		// useful for debuging
	 echo "Current (milliseconds): ${currentTimeMillis}"    
     echo "AWS most recent start (milliseconds): ${timestampMillis}"
	 echo "Elapsed Time (milliseconds): ${elapsedMillis}"
     echo "Elapsed Time (minutes): ${elapsedMinutes}"

    echo "ECS service has been running since last deployment for $elapsedMinutes minutes."

    if (elapsedMinutes > 10) {
        echo "Restarting ECS service..."
        def serviceName = "${env.SERVICE_PREFIX}".split('-')[-1]
        def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
        def data = new URL("http://10.200.2.179/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
        def retList = new JsonSlurper().parseText(data) // Since retList contains only one value, assign it to the global awsRegion variable 
        awsRegion = retList[0]        
        sh """
              aws ecs update-service --region ${awsRegion} --profile ${awsProfile} --cluster ${CLUSTER_NAME} --service ${serviceName} --force-new-deployment
        """
        echo "ECS service has been restarted."
    } else {
        echo "No need to restart ECS service as it has not been running for 10 minutes yet."
    }
}
