import groovy.json.JsonSlurper
pipeline {
    agent {
          ecs {
                inheritFrom "jenkins-agent"
                 }
            }  
    environment {
        ECS_CLUSTER_NAME = "${env.CLUSTER}"
        STATE = "${env.STATE}"
    }

    stages {
        stage('Set ECS Service Desired Count to 0 or 1') {
            steps {
                script {
                    // List ECS services and update their desired count to 0
                    def awsProfile = "Ops_DMS"
                    def awsRegion = "us-east-1"
                    echo "${awsProfile}"
                    def services = sh(script: "aws --profile ${awsProfile} --region ${awsRegion} ecs list-services --cluster ${env.CLUSTER.replaceAll(",", "")} | jq -r '.serviceArns[]' | xargs -n 1 aws --profile ${awsProfile} --region ${awsRegion} ecs update-service --cluster ${env.CLUSTER.replaceAll(",", "")} --desired-count ${env.STATE} --service", returnStdout: true).trim()
                    echo "Updated the desired count to ${env.STATE} for the following ECS services:"
                    echo "${services}"
                }
            }
        }
    }

    post {
        success {
            echo "ECS services in ${CLUSTER} have been set to ${env.STATE} successfully."
        }

        failure {
            echo "Failed to update ECS services to ${env.STATE} in ${CLUSTER}. Check the logs for details."
        }
    }
}
