import groovy.json.JsonSlurper
pipeline {
    agent {
          ecs {
                inheritFrom "jenkins-agent"
                 }
            } 
    environment {
        AWS_DEFAULT_REGION = "us-east-1"
        ENVIRONMENT = "${env.ENVIRONMENT}"
        REDIS_CLUSTER_NAME = "${env.REDIS_CLUSTER_NAME}"
    }

    stages {
        stage('Redis Failover test') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def redisClusterName = env.REDIS_CLUSTER_NAME.replaceAll(",", "")
                    def data = new URL("http://10.200.2.219/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) 
                    awsRegion = retList[0]
                    sh """
                        export AWS_PROFILE=${awsProfile}
                        aws --profile ${awsProfile} --region ${awsRegion} elasticache test-failover --replication-group-id ${redisClusterName} --node-group-id "0001"
                    """
                }
            }
        }

        stage('Status update') {
            steps {
                script {
                    def awsProfile = env.ENVIRONMENT.replaceFirst(/-(QA|TEST|INT|PERF)$/, '')
                    def redisClusterName = env.REDIS_CLUSTER_NAME.replaceAll(",", "")
                    def data = new URL("http://10.200.2.219/active-choice/aws-region.php?awsenv=" + ENVIRONMENT).getText() 
                    def retList = new JsonSlurper().parseText(data) 
                    awsRegion = retList[0]
                    
                    sh """
                        export AWS_PROFILE=${awsProfile}
                        sleep 15
                        aws --profile ${awsProfile}  --region ${awsRegion} elasticache describe-replication-groups --replication-group-id ${redisClusterName}
                        sleep 120
                        aws --profile ${awsProfile}  --region ${awsRegion} elasticache describe-replication-groups --replication-group-id ${redisClusterName}
                    """
                }
            }
        }
    }
}
